### ISSUE TITLE
Note-off events seem to be ignored

### ISSUE THREAD

**Issue by dromer** [folkertvanheusden/fynth#1]
this leads to stuck notes and obviously is not expected.

**Comment by folkertvanheusden** [comment]
Indeed it does.
I thought I read somewhere(?) that 0x80 is merely a hint. Like: if your instrument has an ending, start with that now.
And that for everything else, things only stop when velocity is set to 0.

**Comment by folkertvanheusden** [comment]
I believe it has been fixed in 0cd81557d88bd759b601c3f6575947fb5fd12ced

**Comment by dromer** [comment]
Seems so :)
